version: '3.8'

services:
  web:
    build: .
    command: gunicorn -w 20 -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:7860 --timeout 120 --graceful-timeout 30 main:app
    ports:
      - "7860:7860"
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - MONGO_URL=${MONGO_URL}
      - DB_NAME=${DB_NAME}
    volumes:
      - .:/app
    depends_on:
      - mongo
      - redis
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7860/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s

  worker:
    build: .
    command: celery -A core.background_task worker --loglevel=info --pool=eventlet --concurrency=10
    environment:
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - CELERY_RESULT_BACKEND=${CELERY_RESULT_BACKEND}
      - MONGO_URL=${MONGO_URL}
      - DB_NAME=${DB_NAME}
    volumes:
      - .:/app
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mongo_data:
  redis_data:
