# ============================================================================
# JOBS REPOSITORY
# ============================================================================
# This file was auto-generated on: 2025-09-27 09:11:00 WAT
# It contains asynchronous functions for managing access to the database
# in a MongoDB database using FastAPI.
#
# DO NOT EDIT THIS FILE MANUALLY - RE-RUN THE GENERATOR INSTEAD. OR IF YOU WANT TO EDIT JUST ADD LEAVE OTHER FUNCTIONS THE WAY YOU MET THEM
# ============================================================================

from pymongo import ReturnDocument
from core.database import db
from fastapi import HTTPException,status
from typing import List,Optional
from schemas.jobs import JobsUpdate, JobsCreate, JobsOut

async def create_jobs(jobs_data: JobsCreate) -> JobsOut:
    jobs_dict = jobs_data.model_dump()
    result =await db.jobss.insert_one(jobs_dict)
    result = await db.jobss.find_one(filter={"_id":result.inserted_id})
    returnable_result = JobsOut(**result)
    return returnable_result

async def get_jobs(filter_dict: dict) -> Optional[JobsOut]:
    try:
        result = await db.jobss.find_one(filter_dict)

        if result is None:
            return None

        return JobsOut(**result)

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching jobs: {str(e)}"
        )
    
async def get_jobss(filter_dict: dict = {},start=0,stop=100) -> List[JobsOut]:
    try:
        if filter_dict is None:
            filter_dict = {}

        cursor = (db.jobss.find(filter_dict)
        .skip(start)
        .limit(stop - start)
        )
        jobs_list = []

        async for doc in cursor:
            jobs_list.append(JobsOut(**doc))

        return jobs_list

    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"An error occurred while fetching jobss: {str(e)}"
        )
async def update_jobs(filter_dict: dict, jobs_data: JobsUpdate) -> JobsOut:
    result = await db.jobss.find_one_and_update(
        filter_dict,
        {"$set": jobs_data.model_dump(exclude_none=True)},
        return_document=ReturnDocument.AFTER
    )
    returnable_result = JobsOut(**result)
    return returnable_result

async def delete_jobs(filter_dict: dict):
    return await db.jobss.delete_one(filter_dict)